/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import hilos.RandomG;
import java.awt.Shape;
import java.awt.Window;
import java.awt.geom.RoundRectangle2D;
import java.util.Arrays;
import javax.swing.JOptionPane;
import rojeru_san.complementos.RSEffectFade;
import suma_sub_conjuntos.Metodos_conj;

/**
 *
 * @author Kevin Benitez
 */
public class ChConj extends javax.swing.JFrame
{

    public static Window vtn;

    RandomG rnd;
    public static int[] arr;
    public static int suma;
    Metodos_conj opera;

    /**
     * Creates new form ChOption
     *
     * @param metodo
     */
    public ChConj(String metodo)
    {
        vtn = this;
        initComponents();
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        vtn.setShape(forma);
        RSEffectFade.setFadeWindowIn(this, 30, 0.1f);
        lblMod.setText("Modo seleccionado: " + metodo);
        // 248 limite de frente
        // 6 limite atras
        if (metodo.equals("auto"))
        {
            lblMod.setText("Modo seleccionado: automatico");
            lblTitulo.setText("Aleatorizando conjunto de numeros");
            txtConjunto.setEditable(false);
            rnd = new RandomG(txtConjunto);
            rnd.iniciar();
        }
        if (metodo.equals("manual"))
        {
            btnHiloR.setVisible(false);
        }
    }

    public ChConj()
    {

    }
    
    public void bloqueaComp()
    {
        lblTitulo.setEnabled(false);
        txtConjunto.setText(null);
        txtConjunto.setEnabled(false);
        txtSuma.setText(null);
        txtSuma.setEnabled(false);
        lblMod.setText(null);
        lblMod.setEnabled(false);
        lblSuma.setEnabled(false);
        btnConfirmar.setEnabled(false);
        btnHiloR.setEnabled(false);
        btnAtrasConj.setEnabled(false);
        vtn.setOpacity(0.1f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new RSMaterialComponent.RSLabelTextIcon();
        btnConfirmar = new RSMaterialComponent.RSButtonMaterialOne();
        lblMod = new javax.swing.JLabel();
        btnAtrasConj = new RSMaterialComponent.RSButtonIconOne();
        txtConjunto = new RSMaterialComponent.RSTextFieldMaterial();
        btnHiloR = new RSMaterialComponent.RSButtonMaterialOne();
        txtSuma = new RSMaterialComponent.RSTextFieldMaterial();
        lblSuma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.1F);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setText("Ingrese conjunto de numeros");
        lblTitulo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 102));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBackgroundHover(new java.awt.Color(0, 153, 153));
        btnConfirmar.setEnabled(false);
        btnConfirmar.setRound(10);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblMod.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblMod.setForeground(new java.awt.Color(0, 102, 102));
        lblMod.setText("Modo seleccionado: ");

        btnAtrasConj.setBackground(new java.awt.Color(0, 102, 102));
        btnAtrasConj.setBackgroundHover(new java.awt.Color(0, 153, 153));
        btnAtrasConj.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ARROW_BACK);
        btnAtrasConj.setRound(10);
        btnAtrasConj.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAtrasConjActionPerformed(evt);
            }
        });

        txtConjunto.setForeground(new java.awt.Color(0, 102, 102));
        txtConjunto.setColorMaterial(new java.awt.Color(0, 153, 153));
        txtConjunto.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtConjunto.setPhColor(new java.awt.Color(0, 102, 102));
        txtConjunto.setPlaceholder("Numeros separados por coma");
        txtConjunto.setSelectionColor(new java.awt.Color(0, 102, 102));
        txtConjunto.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtConjuntoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtConjuntoKeyTyped(evt);
            }
        });

        btnHiloR.setBackground(new java.awt.Color(0, 102, 102));
        btnHiloR.setText("Pausar");
        btnHiloR.setBackgroundHover(new java.awt.Color(0, 153, 153));
        btnHiloR.setRound(10);
        btnHiloR.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnHiloRActionPerformed(evt);
            }
        });

        txtSuma.setForeground(new java.awt.Color(0, 102, 102));
        txtSuma.setColorMaterial(new java.awt.Color(0, 153, 153));
        txtSuma.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        txtSuma.setPhColor(new java.awt.Color(0, 102, 102));
        txtSuma.setPlaceholder("Suma requerida");
        txtSuma.setSelectionColor(new java.awt.Color(0, 102, 102));
        txtSuma.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtSumaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtSumaKeyTyped(evt);
            }
        });

        lblSuma.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblSuma.setForeground(new java.awt.Color(0, 102, 102));
        lblSuma.setText("Suma:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtrasConj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblMod, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnHiloR, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtConjunto, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConjunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHiloR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSuma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMod, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtrasConj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasConjActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAtrasConjActionPerformed
    {//GEN-HEADEREND:event_btnAtrasConjActionPerformed
        ChOption.bloq_unloccomp(true);
        if (btnHiloR.isVisible())
        {
            rnd.stop();
        }

        dispose();
    }//GEN-LAST:event_btnAtrasConjActionPerformed

    private void btnHiloRActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnHiloRActionPerformed
    {//GEN-HEADEREND:event_btnHiloRActionPerformed
        if (btnHiloR.getText().equals("Pausar"))
        {
            btnHiloR.setText("Continuar");
            rnd.pausa();
        } else
        {
            if (btnHiloR.getText().equals("Continuar"))
            {
                btnHiloR.setText("Pausar");
                rnd.resume();
            }
        }
    }//GEN-LAST:event_btnHiloRActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmarActionPerformed
    {//GEN-HEADEREND:event_btnConfirmarActionPerformed

        //Si el arreglo se genera automaticamente con el hilo
        if (btnHiloR.isVisible())
        {
            System.out.println("Arreglo: " + Arrays.toString(arr));
            for (int i = 0; i < arr.length; i++)
            {
                System.out.println(arr[i]);
            }
            rnd.stop();
            opera = new Metodos_conj();
            String s = "\nSubconjuntos encontrados: \n\n" + opera.encuentra_conj(arr, suma);
            if (s.equals(""))
            {
                bloqueaComp();
                JOptionPane.showMessageDialog(vtn, "Sin resultados");
            } else
            {
                bloqueaComp();
                VResultados res = new VResultados(s, Arrays.toString(arr), String.valueOf(suma));
                res.setLocation(909, 702);
                res.setVisible(true);
            }

        } else
        {
            //Si el arreglo se introduce de forma manual
            arr = Metodos_conj.conversor(txtConjunto.getText());
            System.out.println("Arreglo: " + Arrays.toString(arr));
            for (int i = 0; i < arr.length; i++)
            {
                System.out.println(arr[i]);
            }
            opera = new Metodos_conj();
            String s = "\nSubconjuntos encontrados: \n\n" + opera.encuentra_conj(arr, suma);
            if (s.equals(""))
            {
                bloqueaComp();
                JOptionPane.showMessageDialog(vtn, "Sin resultados");
            } else
            {
                bloqueaComp();
                VResultados res = new VResultados(s, Arrays.toString(arr), String.valueOf(suma));
                res.setLocation(909, 702);
                res.setVisible(true);
            }
        }

    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void txtSumaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtSumaKeyTyped
    {//GEN-HEADEREND:event_txtSumaKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != evt.VK_BACK_SPACE))
        {
            evt.consume();
        }

        if (txtSuma.getText().length() == 3)
        {
            evt.consume();
        }


    }//GEN-LAST:event_txtSumaKeyTyped

    private void txtConjuntoKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtConjuntoKeyTyped
    {//GEN-HEADEREND:event_txtConjuntoKeyTyped
        char caracter = evt.getKeyChar();

        if (((caracter < '0') || (caracter > '9')) && ((caracter < ',') || (caracter > ',')) && ((caracter < '-' || caracter > '-')) && (caracter != evt.VK_BACK_SPACE))
        {
            evt.consume();
        }

        if (txtConjunto.getText().length() == 35)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtConjuntoKeyTyped

    private void txtSumaKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtSumaKeyReleased
    {//GEN-HEADEREND:event_txtSumaKeyReleased
        if ((txtConjunto.getText().matches("((-?[\\d]+,)+-?[\\d]+)") && (!txtSuma.getText().isEmpty())) || (btnHiloR.isVisible() && (!txtSuma.getText().isEmpty())))
        {
            suma = Integer.parseInt(txtSuma.getText());
            btnConfirmar.setEnabled(true);
        } else
        {
            btnConfirmar.setEnabled(false);
        }
    }//GEN-LAST:event_txtSumaKeyReleased

    private void txtConjuntoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtConjuntoKeyReleased
    {//GEN-HEADEREND:event_txtConjuntoKeyReleased
        if ((!txtSuma.getText().isEmpty()) && txtConjunto.getText().matches("((-?[\\d]+,)+-?[\\d]+)") || (btnHiloR.isVisible() && (!txtSuma.getText().isEmpty())))
        {
            btnConfirmar.setEnabled(true);
        } else
        {
            btnConfirmar.setEnabled(false);
        }
    }//GEN-LAST:event_txtConjuntoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ChConj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ChConj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ChConj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ChConj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ChConj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonIconOne btnAtrasConj;
    private RSMaterialComponent.RSButtonMaterialOne btnConfirmar;
    private RSMaterialComponent.RSButtonMaterialOne btnHiloR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMod;
    private javax.swing.JLabel lblSuma;
    private RSMaterialComponent.RSLabelTextIcon lblTitulo;
    private RSMaterialComponent.RSTextFieldMaterial txtConjunto;
    private RSMaterialComponent.RSTextFieldMaterial txtSuma;
    // End of variables declaration//GEN-END:variables
}
