/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Shape;
import java.awt.Window;
import java.awt.geom.RoundRectangle2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import rojeru_san.complementos.RSEffectFade;

/**
 *
 * @author Kevin Benitez
 */
public class ChOption extends javax.swing.JFrame
{

    public static Window vtn;

    boolean alFrente = false;
    boolean alBack = false;
   

    /**
     * Creates new form ChOption
     */
    public ChOption()
    {
        vtn = this;
        initComponents();
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        vtn.setShape(forma);
        RSEffectFade.setFadeWindowIn(this, 30, 0.1f);
        swOptA.setActivado(false);
        swOptM.setActivado(false);
        System.out.println(vtn.getLocation());
        // 248 limite de frente
        // 6 limite atras

        new Thread()
        {
            public void run()
            {
                int x = 149;
                while (true)
                {
                    if (alBack == true)
                    {
                        x--;
                    } else
                    {
                        if (alFrente == true);
                        {
                            x++;
                        }
                    }

                    if (x > 248)
                    {
                        alBack = true;
                        alFrente = false;
                    }

                    if (x < 3)
                    {
                        alFrente = true;
                        alBack = false;
                    }

                    lblTitulo.setLocation(x, 6);
                    try
                    {
                        sleep(10);
                    } catch (InterruptedException ex)
                    {
                        Logger.getLogger(ChOption.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo11 = new RSMaterialComponent.RSLabelTextIcon();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        swOptA = new RSMaterialComponent.RSSwitch();
        lblTitulo = new RSMaterialComponent.RSLabelTextIcon();
        lblTitulo2 = new RSMaterialComponent.RSLabelTextIcon();
        swOptM = new RSMaterialComponent.RSSwitch();
        btnConfirmar = new RSMaterialComponent.RSButtonMaterialOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.1F);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo11.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo11.setText("Modo manual");
        lblTitulo11.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.KEYBOARD);

        rSButtonIconOne1.setBackground(new java.awt.Color(204, 0, 51));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(153, 51, 0));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        rSButtonIconOne1.setRound(10);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });

        swOptA.setBgOn(new java.awt.Color(0, 102, 102));
        swOptA.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                swOptAMouseClicked(evt);
            }
        });

        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setText("Suma de subconjuntos");
        lblTitulo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);

        lblTitulo2.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo2.setText("Modo automatico");
        lblTitulo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.AUTORENEW);

        swOptM.setBgOn(new java.awt.Color(0, 102, 102));
        swOptM.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                swOptMMouseClicked(evt);
            }
        });

        btnConfirmar.setBackground(new java.awt.Color(0, 102, 102));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.setBackgroundHover(new java.awt.Color(0, 153, 153));
        btnConfirmar.setEnabled(false);
        btnConfirmar.setRound(10);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(swOptA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(swOptM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(rSButtonIconOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonIconOne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(swOptM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(swOptA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
    {//GEN-HEADEREND:event_rSButtonIconOne1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void swOptAMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_swOptAMouseClicked
    {//GEN-HEADEREND:event_swOptAMouseClicked
        if (swOptA.isActivado())
        {
            swOptM.setActivado(false);
            btnConfirmar.setEnabled(true);
        } else
        {
            if (!swOptM.isActivado())
            {
                btnConfirmar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_swOptAMouseClicked

    private void swOptMMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_swOptMMouseClicked
    {//GEN-HEADEREND:event_swOptMMouseClicked
        if (swOptM.isActivado())
        {
            swOptA.setActivado(false);
            btnConfirmar.setEnabled(true);
        } else
        {
            if (!swOptA.isActivado())
            {
                btnConfirmar.setEnabled(false);
            }
        }

    }//GEN-LAST:event_swOptMMouseClicked

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmarActionPerformed
    {//GEN-HEADEREND:event_btnConfirmarActionPerformed
        if (swOptA.isActivado())
        {
            bloq_unloccomp(false);
            ChConj conj = new ChConj("auto");
            conj.setLocation(1250, 396);
            conj.setVisible(true);

        } else
        {
            if (swOptM.isActivado())
            {
                bloq_unloccomp(false);
                ChConj conj = new ChConj("manual");
                conj.setLocation(1250, 396);
                conj.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    public static void bloq_unloccomp(boolean val)
    {
        lblTitulo.setEnabled(val);
        lblTitulo11.setEnabled(val);
        lblTitulo2.setEnabled(val);
        btnConfirmar.setEnabled(false);
        swOptA.setEnabled(val);
        swOptM.setEnabled(val);
        swOptA.setActivado(false);
        swOptM.setActivado(false);
        if (val==true)
        {
            vtn.setOpacity(1);
        }else
        {
            vtn.setOpacity(0.1f);
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ChOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ChOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ChOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ChOption.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new ChOption().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static RSMaterialComponent.RSButtonMaterialOne btnConfirmar;
    private javax.swing.JPanel jPanel1;
    private static RSMaterialComponent.RSLabelTextIcon lblTitulo;
    private static RSMaterialComponent.RSLabelTextIcon lblTitulo11;
    private static RSMaterialComponent.RSLabelTextIcon lblTitulo2;
    private static RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private static RSMaterialComponent.RSSwitch swOptA;
    private static RSMaterialComponent.RSSwitch swOptM;
    // End of variables declaration//GEN-END:variables
}
