/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Shape;
import java.awt.Window;
import java.awt.geom.RoundRectangle2D;
import java.util.logging.Level;
import java.util.logging.Logger;
import rojeru_san.complementos.RSEffectFade;

/**
 *
 * @author Kevin Benitez
 */
public class VResultadosM extends javax.swing.JFrame
{

    public Window vtn;

    boolean alFrente = false;
    boolean alBack = false;
    boolean detener = false;
    String resultado;
    String suma;
    String arreglo;

    /**
     * Creates new form ChOption
     *
     * @param s
     * @param arreglo
     * @param suma
     */
    public VResultadosM(String s, String arreglo, String suma)
    {
        this.resultado = s;
        this.arreglo = arreglo;
        this.suma = suma;
        vtn = this;
        initComponents();
        setLocationRelativeTo(null);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        vtn.setShape(forma);
        lblConjuntoF.setText(this.arreglo);
        lblSumaF.setText(this.suma);
        TPResul.setText("Subconjuntos encontrados: \n\n" + s);
        RSEffectFade.setFadeWindowIn(this, 30, 0.1f);
        // 248 limite de frente
        // 6 limite atras

        new Thread()
        {
            public void run()
            {
                int x2 = 149;

                while (detener != true)
                {
                    if (alBack == true)
                    {
                        x2--;
                    } else
                    {
                        if (alFrente == true);
                        {
                            x2++;
                        }
                    }

                    if (x2 > 476)
                    {
                        alBack = true;
                        alFrente = false;
                    }

                    if (x2 < 3)
                    {
                        alFrente = true;
                        alBack = false;
                    }

                    lblTitulo.setLocation(x2, 6);
                    try
                    {
                        sleep(10);
                    } catch (InterruptedException ex)
                    {
                        Logger.getLogger(VResultadosM.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }.start();
    }

    public VResultadosM()
    {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new RSMaterialComponent.RSLabelTextIcon();
        jScrollPane2 = new javax.swing.JScrollPane();
        TPResul = new javax.swing.JTextPane();
        lblSuma1 = new javax.swing.JLabel();
        lblConjuntoF = new javax.swing.JLabel();
        lblSuma3 = new javax.swing.JLabel();
        lblSumaF = new javax.swing.JLabel();
        btnReset = new RSMaterialComponent.RSButtonIconOne();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.1F);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setForeground(new java.awt.Color(0, 102, 102));
        lblTitulo.setText("Resultados obtenidos");
        lblTitulo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REPORT);

        TPResul.setEditable(false);
        TPResul.setBackground(new java.awt.Color(255, 255, 255));
        TPResul.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        TPResul.setForeground(new java.awt.Color(0, 102, 102));
        TPResul.setFocusable(false);
        TPResul.setSelectionColor(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(TPResul);

        lblSuma1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblSuma1.setForeground(new java.awt.Color(0, 102, 102));
        lblSuma1.setText("Conjunto proporcionado");

        lblConjuntoF.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblConjuntoF.setForeground(new java.awt.Color(0, 102, 102));
        lblConjuntoF.setText("Conjunto");

        lblSuma3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblSuma3.setForeground(new java.awt.Color(0, 102, 102));
        lblSuma3.setText("Suma:");

        lblSumaF.setFont(new java.awt.Font("Segoe UI Semibold", 1, 13)); // NOI18N
        lblSumaF.setForeground(new java.awt.Color(0, 102, 102));
        lblSumaF.setText("Suma proporcionada");

        btnReset.setBackground(new java.awt.Color(0, 102, 102));
        btnReset.setBackgroundHover(new java.awt.Color(0, 153, 153));
        btnReset.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.REFRESH);
        btnReset.setRound(10);
        btnReset.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSuma3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSuma1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addComponent(lblConjuntoF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSumaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSuma1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblConjuntoF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSuma3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSumaF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnResetActionPerformed
    {//GEN-HEADEREND:event_btnResetActionPerformed
        ChConj.vtn.dispose();
        detener = true;
        dispose();
        ChOption.bloq_unloccomp(true);
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VResultadosM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VResultadosM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VResultadosM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VResultadosM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new VResultadosM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TPResul;
    private RSMaterialComponent.RSButtonIconOne btnReset;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConjuntoF;
    private javax.swing.JLabel lblSuma1;
    private javax.swing.JLabel lblSuma3;
    private javax.swing.JLabel lblSumaF;
    private static RSMaterialComponent.RSLabelTextIcon lblTitulo;
    // End of variables declaration//GEN-END:variables
}
